name: Build and Test

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Upload Build (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: carrotmq-rabbitmq-build-windows
        path: |
          TestApp/bin
          TestApp.Test/bin

  test-ubuntu:
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Build (Debug)
      uses: actions/download-artifact@v4
      with:
        name: carrotmq-rabbitmq-build-windows
        path: |
          TestApp/bin
          TestApp.Test/bin

    - name: Test
      run: dotnet test --no-build --verbosity normal